from typing import Any

class SessionManager:
    def __init__(self) -> None: ...
    def prepare_models(self, engine: Any) -> None: ...
    def session_factory(
        self, dburi: str, **kwargs: Any
    ) -> Any: ...
