from collections.abc import Callable
from typing import Any

from celery.backends.base import Backend

class AsyncBackendMixin:
    @property
    def is_async(self) -> bool: ...
    def wait_for_pending(
        self,
        result: Any,
        callback: Callable[..., Any] | None = None,
        propagate: bool = True,
        **kwargs: Any,
    ) -> Any: ...
    def add_pending_result(
        self, result: Any, weak: bool = False, start_drainer: bool = True
    ) -> Any: ...
    def add_pending_results(self, results: list[Any], weak: bool = False) -> None: ...
    def remove_pending_result(self, result: Any) -> None: ...
    def on_result_fulfilled(self, result: Any) -> None: ...
    def iter_native(self, result: Any, no_ack: bool = True, **kwargs: Any) -> Any: ...

class BaseResultConsumer:
    def __init__(
        self,
        backend: Backend,
        app: Any,
        accept: Any,
        pending_results: Any,
        pending_messages: Any,
    ) -> None: ...
    def start(self, initial_task_id: str, **kwargs: Any) -> None: ...
    def stop(self) -> None: ...
    def drain_events(self, timeout: float | None = None) -> None: ...
    def consume_from(self, task_id: str) -> None: ...
    def cancel_for(self, task_id: str) -> None: ...
    def on_state_change(self, meta: dict[str, Any], message: Any) -> None: ...
