from collections.abc import Callable
from typing import Any

from celery.backends.base import Backend

class AsyncBackendMixin:
    def wait_for_pending(
        self,
        result: Any,
        callback: Callable[..., Any] | None = None,
        propagate: bool = True,
        **kwargs: Any,
    ) -> Any: ...
    def add_pending_result(
        self, result: Any, weak: bool = False, start: bool = True
    ) -> Any: ...
    def remove_pending_result(self, result: Any) -> None: ...
    def drain_events_until(
        self,
        p: Callable[[], bool],
        on_interval: Callable[..., Any] | None = None,
        wait: float | None = None,
        timeout: float | None = None,
    ) -> None: ...
    def on_result_fulfilled(self, result: Any) -> None: ...
    def ensure_chords_allowed(self) -> None: ...

class BaseResultConsumer:
    def __init__(self, backend: Backend, **kwargs: Any) -> None: ...
    def start(self, initial_task_id: str | None = None, **kwargs: Any) -> None: ...
    def stop(self) -> None: ...
    def drain_events(self, timeout: float | None = None) -> None: ...
    def consume_from(self, task_id: str) -> None: ...
    def cancel_for(self, task_id: str) -> None: ...
    def on_state_change(self, meta: dict[str, Any], message: Any) -> None: ...
