from collections.abc import Callable, Iterable, Sequence
from typing import Any, TypeVar

import kombu
from kombu.utils.uuid import uuid as uuid

__all__: tuple[str, ...]

LOG_LEVELS: dict[str, int]
_T = TypeVar("_T")

def cached_property(f: Callable[[Any], _T]) -> _T: ...
def chunks(it: Iterable[_T], n: int) -> Iterable[Sequence[_T]]: ...
def gen_task_name(app: Any, name: str, module_name: str) -> str: ...
def gen_unique_id() -> str: ...
def get_cls_by_name(
    name: str,
    aliases: dict[str, str] | None = None,
    imp: Any = None,
    package: str | None = None,
    **kwargs: Any,
) -> Any: ...
def get_full_cls_name(cls: type, reverse: bool = True) -> str: ...
def import_from_cwd(
    module: str, imp: Any = None, package: str | None = None
) -> Any: ...
def instantiate(name: str, *args: Any, **kwargs: Any) -> Any: ...
def memoize(
    maxsize: int = 128,
    keyfun: Callable[..., Any] | None = None,
    Cache: type | None = None,
) -> Callable[[Callable[..., _T]], Callable[..., _T]]: ...
def nodename(name: str, hostname: str) -> str: ...
def nodenames(names: Iterable[str], hostname: str) -> list[str]: ...
def nodesplit(name: str) -> tuple[None, str] | list[str]: ...
def noop(*args: Any, **kwargs: Any) -> None: ...
def worker_direct(hostname: str | kombu.Queue) -> kombu.Queue: ...
