from typing import Any

def annotation_is_class(x: Any) -> bool: ...
def annotation_issubclass(x: Any, cls: type) -> bool: ...
def get_optional_arg(annotation: Any) -> Any: ...
def is_none_type(x: Any) -> bool: ...
