from typing import Any

class UnpickleableExceptionWrapper(Exception):
    exc_module: str
    exc_name: str
    exc_args: tuple[Any, ...]

    def __init__(
        self,
        exc_module: str,
        exc_name: str,
        exc_args: tuple[Any, ...],
        text: str = "",
    ) -> None: ...
    def restore(self) -> Exception: ...

class SerializerError(Exception): ...
class ContentDisallowed(SerializerError): ...

def strtobool(term: str | bool | int | None) -> bool: ...
def get_pickled_exception(exc: Exception) -> Exception: ...
def ensure_allowed(allowed: set[str], content_type: str) -> None: ...
def jsonify(obj: Any) -> Any: ...
def raise_with_context(exc: Exception) -> None: ...
def find_pickleable_exception(
    exc: Exception,
    loads: Any = ...,
    dumps: Any = ...,
) -> Exception | None: ...
def ensure_serializable(objects: list[Any], encoder: Any) -> list[Any]: ...
def create_exception_cls(name: str, module: str, parent: type | None = None) -> type[Exception]: ...
