from collections.abc import Callable, Iterable
from typing import Any

def abbr(S: str, max: int, ellipsis: str = "...") -> str: ...
def abbrtask(S: str, max: int) -> str: ...
def dedent(s: str, n: int = 4, sep: str = "\n") -> str: ...
def dedent_initial(s: str, n: int = 4) -> str: ...
def ensure_newlines(s: str) -> str: ...
def fill_paragraphs(s: str, width: int, sep: str = "\n\n") -> str: ...
def indent(t: str, indent: int = 0, sep: str = "\n") -> str: ...
def join(l: Iterable[str], sep: str = "\n") -> str: ...
def pluralize(n: int, text: str, suffix: str = "s") -> str: ...
def pretty(
    value: Any, width: int = 80, nl_width: int = 80, sep: str = "\n", **kw: Any
) -> str: ...
def simple_format(
    s: str,
    keys: dict[str, Any],
    pattern: str = ...,
    expand: Callable[[str, str], str] = ...,
) -> str: ...
def truncate(s: str, maxlen: int = 128, suffix: str = "...") -> str: ...
