from typing import Any

from celery import bootsteps

__all__ = ("Beat", "Consumer", "Hub", "Pool", "StateDB", "Timer")

class Timer(bootsteps.Step):
    def __init__(self, parent: Any, **kwargs: Any) -> None: ...
    def create(self, w: Any) -> Any: ...
    def on_timer_error(self, exc: Exception) -> None: ...
    def on_timer_tick(self, delay: float) -> None: ...

class Hub(bootsteps.StartStopStep):
    def __init__(self, w: Any, **kwargs: Any) -> None: ...
    def create(self, w: Any) -> Any: ...
    def include_if(self, w: Any) -> bool: ...
    def start(self, w: Any) -> None: ...
    def stop(self, w: Any) -> None: ...
    def terminate(self, w: Any) -> None: ...

class Pool(bootsteps.StartStopStep):
    def __init__(
        self, w: Any, autoscale: tuple[int, int] | None = None, **kwargs: Any
    ) -> None: ...
    def close(self, w: Any) -> None: ...
    def create(self, w: Any) -> Any: ...
    def info(self, w: Any) -> dict[str, Any]: ...  # type: ignore[override]
    def register_with_event_loop(self, w: Any, hub: Any) -> None: ...
    def terminate(self, w: Any) -> None: ...

class Beat(bootsteps.StartStopStep):
    def __init__(self, w: Any, beat: bool = False, **kwargs: Any) -> None: ...
    def create(self, w: Any) -> Any: ...

class StateDB(bootsteps.Step):
    def __init__(self, w: Any, **kwargs: Any) -> None: ...
    def create(self, w: Any) -> Any: ...

class Consumer(bootsteps.StartStopStep):
    def __init__(self, parent: Any, **kwargs: Any) -> None: ...
    def create(self, w: Any) -> Any: ...
