from typing import Any

class Pidbox:
    consumer: Any
    connection: Any
    node: Any

    def __init__(self, consumer: Any) -> None: ...
    def start(self, consumer: Any) -> None: ...
    def stop(self) -> None: ...
    def reset(self) -> None: ...
    def on_message(self, body: Any, message: Any) -> None: ...
    def on_control(self, body: Any, message: Any) -> None: ...
