from collections.abc import Callable, MutableSet
from typing import Any

class Persistent:
    db: Any
    merge: Callable[..., Any]
    open: Callable[..., Any]

    def __init__(self, state: Any, filename: str, clock: Any | None = None) -> None: ...
    def save(self) -> None: ...

revoked: MutableSet[str]
revoked_stamps: dict[str, set[str]]
active_requests: MutableSet[Any]
reserved_requests: MutableSet[Any]
total_count: dict[str, int]
task_count: int

def should_stop() -> bool: ...
def should_terminate() -> bool: ...
def maybe_shutdown() -> None: ...
def reset_state() -> None: ...
def task_accepted(request: Any, _all_total_count: list[int] = ...) -> None: ...
def task_reserved(request: Any) -> None: ...
def task_ready(request: Any) -> None: ...
