from collections.abc import Callable
from typing import Any

import kombu
from celery.app.base import Celery
from celery.bootsteps import Blueprint

class Consumer:
    app: Celery
    hostname: str
    pool: Any
    connection: kombu.Connection | None
    blueprint: Blueprint

    def __init__(
        self,
        on_task_request: Callable[..., Any],
        hostname: str | None = None,
        pool: Any = None,
        app: Celery | None = None,
        timer: Any = None,
        controller: Any = None,
        hub: Any = None,
        amqheartbeat: float | None = None,
        worker_options: dict[str, Any] | None = None,
        disable_rate_limits: bool = False,
        initial_prefetch_count: int = 2,
        prefetch_multiplier: int = 4,
        **kwargs: Any,
    ) -> None: ...
    Blueprint: type[Blueprint]
    Strategies: dict[str, Any]
    restart_count: int

    def bucket_for_task(self, type: Any) -> Any: ...
    def reset_rate_limits(self) -> None: ...
    def add_task_queue(
        self,
        queue: str | kombu.Queue,
        exchange: str | kombu.Exchange | None = None,
        exchange_type: str | None = None,
        routing_key: str | None = None,
        **options: Any,
    ) -> kombu.Queue: ...
    def cancel_task_queue(self, queue: str | kombu.Queue) -> None: ...
    def apply_eta_task(self, task: Any) -> None: ...
    def broker_connection_retry_attempt(self, exc: Exception) -> None: ...
    def call_soon(
        self,
        callback: Callable[..., Any],
        *args: Any,
        **kwargs: Any,
    ) -> None: ...
    def cancel_active_requests(self) -> None: ...
    def connect(self) -> kombu.Connection: ...
    def connection_for_read(
        self, heartbeat: float | None = None
    ) -> kombu.Connection: ...
    def connection_for_write(
        self, heartbeat: float | None = None
    ) -> kombu.Connection: ...
    def create_task_handler(self, alpha: float | None = None) -> Callable[..., Any]: ...
    def ensure_connected(self, conn: kombu.Connection) -> kombu.Connection: ...
    def first_connection_attempt(self) -> bool: ...
    def init_callback(self, hub: Any) -> None: ...
    @property
    def loop_args(self) -> tuple[Any, ...]: ...
    @property
    def max_prefetch_count(self) -> int: ...
    def on_close(self) -> None: ...
    def on_connection_error_after_connected(
        self, exc: Exception, interval: float
    ) -> None: ...
    def on_connection_error_before_connected(
        self, exc: Exception, interval: float
    ) -> None: ...
    def on_decode_error(self, message: Any, exc: Exception) -> None: ...
    def on_invalid_task(self, message: Any, exc: Exception) -> None: ...
    def on_ready(self) -> None: ...
    def on_send_event_buffered(self) -> Callable[..., Any]: ...
    def on_unknown_message(self, body: Any, message: Any) -> None: ...
    def on_unknown_task(self, message: Any, exc: Exception) -> None: ...
    def perform_pending_operations(self) -> None: ...
    def register_with_event_loop(self, hub: Any) -> None: ...
    def stop(self) -> None: ...
    def start(self) -> None: ...
    def shutdown(self) -> None: ...
    @property
    def timer(self) -> Any: ...
    def update_strategies(self) -> None: ...
