from collections.abc import Callable, Iterator
from contextlib import contextmanager
from logging import Logger
from typing import Any

DAEMON_WORKDIR: str
EX_OK: int
EX_FAILURE: int
EX_UNAVAILABLE: int
EX_USAGE: int

class Signals:
    def arm_alarm(self, seconds: float) -> None: ...
    def default(self, sig: int) -> None: ...
    def ignore(self, *signals: int) -> None: ...
    def ignored(self, sig: int) -> bool: ...
    def reset(self, sig: int) -> None: ...
    def reset_alarm(self) -> None: ...
    def signum(self, sig: int | str) -> int: ...
    def supported(self, sig: int | str) -> bool: ...
    def update(self, signals: dict[int, Callable[[int, Any], None]]) -> None: ...

signals: Signals

def get_fdmax(default: int | None = None) -> int: ...
def close_open_fds(keep: set[int] | None = None) -> None: ...
def fd_by_path(paths: list[str]) -> list[int]: ...
@contextmanager
def ignore_errno(*errnos: int) -> Iterator[None]: ...
def set_process_title(progname: str, info: str | None = None) -> None: ...
def set_mp_process_title(progname: str, info: str | None = None, hostname: str | None = None) -> None: ...
def maybe_drop_privileges(uid: int | str | None = None, gid: int | str | None = None) -> None: ...
def setgroups(groups: list[int]) -> None: ...
def initgroups(uid: int, gid: int) -> None: ...
def setgid(gid: int | str) -> None: ...
def setuid(uid: int | str) -> None: ...
def parse_uid(uid: int | str) -> int: ...
def parse_gid(gid: int | str) -> int: ...
def isatty(fh: Any) -> bool: ...
def detached(
    logfile: str | None = None,
    pidfile: str | None = None,
    uid: int | str | None = None,
    gid: int | str | None = None,
    umask: int = 0,
    workdir: str | None = None,
    fake: bool = False,
    **opts: Any,
) -> Any: ...
def create_pidlock(pidfile: str) -> Any: ...

class DaemonContext:
    open_fds: set[int] | None
    pidfile: str | None
    workdir: str
    umask: int

    def __init__(
        self,
        pidfile: str | None = None,
        workdir: str | None = None,
        umask: int = 0,
        fake: bool = False,
        after_chdir: Callable[[], None] | None = None,
        after_forkers: bool = True,
        **kwargs: Any,
    ) -> None: ...
    def open(self) -> DaemonContext: ...
    def close(self) -> None: ...
    def __enter__(self) -> DaemonContext: ...
    def __exit__(self, *exc_info: Any) -> None: ...

class Pidfile:
    path: str
    def __init__(self, path: str) -> None: ...
    def acquire(self) -> Pidfile: ...
    def is_locked(self) -> bool: ...
    def release(self) -> None: ...
    def read_pid(self) -> int | None: ...
    def remove(self) -> None: ...
    def remove_if_stale(self) -> bool: ...
    def write_pid(self) -> None: ...
    def __enter__(self) -> Pidfile: ...
    def __exit__(self, *exc_info: Any) -> None: ...

class LockFailed(Exception): ...
