from typing import Any

from celery.app.base import Celery

class DjangoFixup:
    app: Celery
    def __init__(self, app: Celery) -> None: ...
    def install(self) -> None: ...
    def on_import_modules(self, **kwargs: Any) -> None: ...
    def on_worker_init(self, **kwargs: Any) -> None: ...
    def on_worker_process_init(self, **kwargs: Any) -> None: ...

def fixup(app: Celery, env: str | None = None) -> DjangoFixup | None: ...
